# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Configures FUSE with user_allow_other - crunch-run depends on this.
# Assumes you've already installed FUSE.

- name: Configure FUSE with user_allow_other
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/fuse.conf
    regexp: "^[# ]*user_allow_other *$"
    line: user_allow_other
