# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: apt update if needed
  ansible.builtin.meta: flush_handlers

- name: Install Arvados Workbench
  become: yes
  ansible.builtin.apt:
    name:
      - arvados-workbench2
