# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: apt update if needed
  ansible.builtin.meta: flush_handlers

- name: Install arvados-ws
  become: yes
  ansible.builtin.apt:
    name:
      - arvados-ws

- name: Start and enable arvados-ws.service
  become: yes
  ansible.builtin.systemd_service:
    name: arvados-ws.service
    state: "{{ 'restarted' if arvados_config_changed else 'started' }}"
    enabled: true
