# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

dependencies:
  - role: arvados_apt
  - role: arvados_docker
  - role: arvados_service
    vars:
      # It's better if config.yml isn't installed on the shell node,
      # so override any existing definition.
      arvados_config_file: null
