# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Install Docker package pins
  become: yes
  ansible.builtin.copy:
    src: arvados-docker.pref
    dest: /etc/apt/preferences.d/arvados-docker.pref
    owner: root
    group: root
    mode: 0644
  when: "arvados_compute_pin_packages|bool"

- name: Install Docker apt repository
  become: yes
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_apt_url }}"
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: "{{ docker_apt_url }}/gpg"
  notify:
    - apt update

- name: apt update if needed
  ansible.builtin.meta: flush_handlers

- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name: docker-ce
    install_recommends: false
