# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

dependencies:
  - role: "{{ 'distro_apt' if (arvados_compute_packages is defined and arvados_compute_packages is falsy) else 'arvados_apt' }}"
