# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Configure Docker daemon
  ansible.builtin.copy:
    content: "{{ docker_daemon|combine({'dns': [dns_resolver]} if dns_resolver is defined else {})|to_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: docker
    mode: 0640

- name: Install Docker cleaner
  ansible.builtin.apt:
    name: arvados-docker-cleaner

- name: Create Docker cleaner configuration directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/arvados
    - /etc/arvados/docker-cleaner

- name: Configure Docker cleaner
  ansible.builtin.copy:
    content: "{{ docker_cleaner|to_json }}"
    dest: /etc/arvados/docker-cleaner/docker-cleaner.json
    owner: root
    group: root
    mode: 0644
