# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Ensure Keepstore Directory roots exist
  become: yes
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0750
  loop: "{{ arvados_cluster.Volumes.values()|selectattr('Driver', '==', 'Directory')|map(attribute='DriverParameters.Root')|unique }}"

- name: apt update if needed
  ansible.builtin.meta: flush_handlers

- name: Install Arvados keepstore
  become: yes
  ansible.builtin.apt:
    name:
      - keepstore

- name: Start and enable keepstore.service
  become: yes
  ansible.builtin.systemd_service:
    name: keepstore.service
    state: "{{ 'restarted' if arvados_config_changed else 'started' }}"
    enabled: true
