# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

docker_daemon:
  data-root: /tmp/docker-data
  default-ulimits:
    nofile:
      Name: nofile
      Soft: 10000
      Hard: 10000
docker_cleaner:
  Quota: 10G
  RemoveStoppedContainers: always
