# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# User and database to set up
arvados_database_name: "{{ arvados_cluster.PostgreSQL.Connection.dbname }}"
arvados_database_user_name: "{{ arvados_cluster.PostgreSQL.Connection.user }}"
arvados_database_user_password: "{{ arvados_cluster.PostgreSQL.Connection.password }}"

# Comma-separated list of `CREATE ROLE WITH` arguments,
# like `CREATEDB`, `NOLOGIN`, etc.
arvados_database_role_attr_flags: ""

# How to connect to the PostgreSQL server.
# If login_host is empty, the role will "become" login_user on the managed node
# to perform database administration.
arvados_database_login_host: "{{ arvados_cluster.PostgreSQL.Connection.host }}"
arvados_database_login_port: "{{ arvados_cluster.PostgreSQL.Connection.port }}"

# Credentials for the PostgreSQL server.
arvados_database_login_user: postgres
arvados_database_login_password: ""
