# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Set up Go directory
  become: yes
  ansible.builtin.file:
    state: directory
    path: "{{ arvados_go_destdir }}"
    owner: root
    group: root
    mode: 0755

- name: Install Go
  become: yes
  ansible.builtin.unarchive:
    src: "https://storage.googleapis.com/golang/go{{ arvados_go_version }}.linux-amd64.tar.gz"
    dest: "{{ arvados_go_destdir }}"
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    creates: "{{ (arvados_go_destdir, 'bin/go')|path_join }}"

- name: Add Go commands to PATH
  become: yes
  ansible.builtin.file:
    state: link
    src: "{{ (arvados_go_destdir, 'bin', item)|path_join }}"
    dest: "{{ ('/usr/local/bin', item)|path_join }}"
  loop:
    - go
    - gofmt
