# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: apt update if needed
  ansible.builtin.meta: flush_handlers

- name: Install Arvados keepproxy
  become: yes
  ansible.builtin.apt:
    name:
      - keepproxy

- name: Start and enable keepproxy.service
  become: yes
  ansible.builtin.systemd_service:
    name: keepproxy.service
    state: "{{ 'restarted' if arvados_config_changed else 'started' }}"
    enabled: true
