# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

name: Arvados Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  workbench2:
    name: Workbench2 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          # true = remove
          # false = keep
          # this might remove tools that are actually needed, (Node, Go, Python, Ruby, ...)
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          # Cleaning up images causes some failure with the docker build/tests
          docker-images: false
          # Keep swap to avoid thrashing unless we really need the space
          swap-storage: false
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Build wb2 test container
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: "services/workbench2/docker/Dockerfile"
          tags: workbench2-test:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run wb2 integration tests
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: workbench2-test:latest
          # Timeout workaround to prevent orphaned browser process https://github.com/cypress-io/cypress/issues/28397
          options: >-
            -v ${{github.workspace}}:/usr/src/arvados
            -w /usr/src/arvados/services/workbench2
            --env CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT=300000
          run: |
            yarn install
            yarn test || exit $?
            tools/run-integration-tests.sh -a /usr/src/arvados
